Content layout
wolox-training/it-angular pull request #3
Opened 2018-06-12 15:16 UTC by tammaroivan

##  Summary

- Content Layout (Front-End & Back-End)

## Screenshot
![image](https://user-images.githubusercontent.com/25356559/41299691-65befe18-6e3a-11e8-97dc-72f0664fed53.png)

![image](https://user-images.githubusercontent.com/25356559/41299709-6c09c35c-6e3a-11e8-9601-ff9425ecf919.png)

## Trello Cards

https://trello.com/c/hwrK1kXb/23-content-layout

2018-06-12 19:41 UTC, FrankIglesias requested changes
Check indentation

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +
delete line

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +  			<p><strong>Release: 2013</strong></p>
add a class to this font weight

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +  			<img src="assets/angular_icon.svg" alt="">
add an alt

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +  			<img src="assets/vue_icon.svg" alt="">
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +  			<p><strong>Release: 2014</strong></p>
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +  			<img src="assets/elm_icon.svg" alt="">
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/index.html
> +
same

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	width: 70%;
use a padding instead of a with with percentage

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	margin: 50px;
use shorthand for this

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +	height: 330px;
use flexbox for this height

2018-06-12 19:41 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +		max-height: 100px;
set a height as auto or delete the width and use a height

2018-06-13 12:39 UTC, tammaroivan commented
New fixes

2018-06-13 15:17 UTC, FrankIglesias requested changes

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/index.html
> +  		<div class="tech">
check indentation

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +.main {
same

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	padding: 0 15%;
use px instead

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	margin: 0 auto;
why this?

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +  font-weight: 600;
font-weight 500?

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +	width: 210px;
check indentation

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/tech.scss
>  	img {
avoid using tags in scss

2018-06-13 15:17 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +		max-height: auto;
use height instead

2018-06-13 17:27 UTC, FrankIglesias requested changes

2018-06-13 17:27 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +  padding: 100px;
remove this, add a margin to the .main class

2018-06-13 17:27 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +.bold {
move this to a `font.scss` file

2018-06-13 17:27 UTC, FrankIglesias commented
resolve conflicts

2018-06-13 17:46 UTC, tammaroivan commented on maquetado/scss/styles.scss
> +.bold {
class .bold moved to scss/font.scss

2018-06-13 19:04 UTC, FrankIglesias approved these changes

2018-06-13 19:19 UTC, merged