Fixed Navbar
wolox-training/it-angular pull request #5
Opened 2018-06-12 16:16 UTC by tammaroivan

## Summary 
- Fixed Navbar

## Screenshot
![image](https://user-images.githubusercontent.com/25356559/41303179-d4e86d80-6e42-11e8-9e6e-7da0eb91a9eb.png)

## Trellos 

https://trello.com/c/gmtTprjV/13-navbar

2018-06-12 19:44 UTC, FrankIglesias requested changes

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +  background: #FFF;
use variable colors

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +  box-shadow: 0px 5px 12px 0px rgba(0,0,0,0.5);
same

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +  z-index: 999999;
z-index :1

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +.navbar img {
dont use tags in html

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +.navbar p {
same

2018-06-12 19:44 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	margin-top: 70px;
use shorthand for margins

2018-06-13 15:20 UTC, FrankIglesias requested changes

2018-06-13 15:20 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +  box-shadow: 0px 5px 12px 0px rgba(0,0,0,0.5);
use a variable color for the last param `rgba(....)`

2018-06-13 15:20 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +.navbar .logo {
nest logo and text inside `.navbar`

2018-06-13 16:42 UTC, tammaroivan commented
Not using tags in previous version (PR Fixes in navbar pr)

2018-06-13 17:29 UTC, FrankIglesias approved these changes

2018-06-13 17:29 UTC, FrankIglesias commented on maquetado/scss/navbar.scss
> +  .text {
I'd use another name to this class.. but it's ok for now

2018-06-13 19:21 UTC, merged