Css grid
wolox-training/it-angular pull request #7
Opened 2018-06-12 18:03 UTC by tammaroivan

## Summary
- New layout using css grid

## Screenshot
![image](https://user-images.githubusercontent.com/25356559/41308224-b7cdb1a6-6e51-11e8-8313-e7e1e075e8bc.png)

## Trello URL

https://trello.com/c/ZvPsjj0C/12-redise%C3%B1o-de-la-p%C3%A1gina

2018-06-12 20:00 UTC, FrankIglesias requested changes

2018-06-12 20:00 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +	display: grid;
check intendtation

2018-06-12 20:00 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +.tech.primary {
define this class inside tech

2018-06-13 15:25 UTC, FrankIglesias requested changes

2018-06-13 15:25 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +  margin: 50px;
use a shorthand for margins

2018-06-13 15:25 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +  img {
don't use tags in scss

2018-06-13 15:25 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +  p {
same

2018-06-13 15:25 UTC, FrankIglesias commented on maquetado/scss/tech.scss
> +  &.primary {
this could also be replaced with [first-child](https://www.w3schools.com/CSSref/sel_firstchild.asp) or [first-of-type](https://www.w3schools.com/cssref/sel_first-of-type.asp)

2018-06-13 16:46 UTC, tammaroivan commented on maquetado/scss/tech.scss
> +  &.primary {
done

2018-06-13 16:50 UTC, tammaroivan commented on maquetado/scss/tech.scss
> +  p {
Fixed tags in previous version

2018-06-13 16:50 UTC, tammaroivan commented on maquetado/scss/tech.scss
> +  img {
Fixed tags in previous version

2018-06-13 17:31 UTC, FrankIglesias requested changes

2018-06-13 17:31 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +  width: 70%;
dont use percentages for width

2018-06-13 17:31 UTC, FrankIglesias commented on maquetado/scss/styles.scss
> +  margin-top: 70px;
use a shorthand

2018-06-13 20:11 UTC, FrankIglesias approved these changes

2018-06-13 20:13 UTC, merged